### ISSUE TITLE
Create .dep files

### ISSUE THREAD

**Issue by atallo** [j-be/attomail#1]
Can you create a .dep file? 

For easy use on ubuntu.

Thanks

**Comment by j-be** [comment]
hey,

maybe - what is a .dep file?

**Comment by atallo** [comment]
Sorry... .deb file...

https://wiki.debian.org/deb

**Comment by j-be** [comment]
Oh, I see. I never built one, and I'm not sure whether that is worth the effort.

Personally, I use Ansible to deploy it. I can provide the Role if that helps.

But it is as simple as:

* Grab the right prebuilt binary from the Release (amd64 and armhf are available)
* Rename it to `sendmail`
* Put it on the `PATH`
* `chown your-user:your-group`
* `chmod 4111 sendmail`

I build the release using GitHub Actions (check out the `.github` folder of this repo), so if you'd like you can provide a PullRequest to add other architectures or Deb package builds to it.

**Comment by atallo** [comment]
Thank you. I'll keep it in mind. 

But with a dep it would be possible to add it to an official repository.
